### ISSUE TITLE
Port the executable code snippets

### ISSUE THREAD

**Issue by jroesch** [leanprover/reference#3]
We should port the Lean book code for executing code snippets using @gebner's new Javascript library for executing Lean.

https://github.com/gebner/lean-server-js

**Comment by gebner** [comment]
FYI, I renamed the library since it is not really a lean server implementation in javascript, but rather a client:
https://github.com/gebner/lean-client-js
https://www.npmjs.com/package/lean-client-js-browser

The next version of gitbook will be based on React, so I think the plugin should target that.

**Comment by avigad** [comment]
This is handled by @gebner's `lean_sphynx.py`.
